apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: maven
  name: maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maven
    spec:
      containers:
      - image: draftaks.azurecr.io/maven
        name: maven
        ports:
        - containerPort: 80
        resources: {}
status: {}
